"$schema" = 'https://starship.rs/config-schema.json'

# Prompt format
add_newline = false
format = """$directory$git_branch$git_status"""
right_format = """$rust$python$nodejs"""

# Colors
palette="catppuccin_mocha"

[palettes.custom]
black = '#484f58'
red = '#ff7b72'
green = '#3fb950'
yellow = '#d29922'
blue = '#58a6ff'
purple = '#bc8cff'
cyan = '#39c5cf'
white = '#b1bac4'
bright_black = '#6e7681'
bright_red = '#ffa198'
bright_green = '#56d364'
bright_yellow = '#e3b341'
bright_blue = '#79c0ff'
bright_purple = '#d2a8ff'
bright_cyan = '#56d4dd'
bright_white = '#ffffff'
node_green = '#3fb950'
python_yellow = '#d29922'
rust_orange = '#ff7b72'
git_orange = '#ffa198'
git_brown = '#e3c38c'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[directory]
style = "blue"
truncation_length = 0
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[rust]
format = "[ ($version) ](rust_orange)"

[python]
format = "[ ($version) ](python_yellow)"

[nodejs]
format = "[ ($version) ](node_green)"

[git_branch]
symbol = " "
format = "[on](white) [ $branch](git_orange) $git_status"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
conflicted = "[=](red)"
ahead = "[⇡${count}](cyan)"
behind = "[⇣${count}](cyan)"
diverged = "[⇕⇡${ahead_count}⇣${behind_count}](purple)"
untracked = "[?${count}](white)"
stashed = "[ ${count}](blue)"
modified = "[!${count}](git_brown)"
staged = "[+${count}](green)"
renamed = "[»${count}](purple)"
deleted = "[✘${count}](red)"

[line_break]
disabled = true

[status]
disabled = false
symbol = ' ✘'
